//
//  PConstants.h
//  FiiiPay
//
//  Created by SongJiang on 8/9/16.
//  Copyright © 2016 Jimmy. All rights reserved.
//

#ifndef PConstants_h
#define PConstants_h

#define MIN_INTERVAL 180
#define MIN_RETRY_INTERVAL 120

#define NOTIFICATION_DOWNLOAD_START @"NOTIFICATION_DOWNLOAD_START"
#define NOTIFICATION_DOWNLOAD_PROGRESS @"NOTIFICATION_DOWNLOAD_PROGRESS"
#define NOTIFICATION_DOWNLOAD_DONE @"NOTIFICATION_DOWNLOAD_DONE"
#define NOTIFICATION_DOWNLOAD_FAILED @"NOTIFICATION_DOWNLOAD_FAILED"
#define NOTIFICATION_PLAY_AUDIO @"NOTIFICATION_PLAY_AUDIO"
#define NOTIFICATION_STOP_AUDIO @"NOTIFICATION_STOP_AUDIO"
#define NOTIFICATION_PAUSE_AUDIO @"NOTIFICATION_PAUSE_AUDIO"
#define NOTIFICATION_RESUME_AUDIO @"NOTIFICATION_RESUME_AUDIO"
#define NOTIFICATION_SEEK_AUDIO @"NOTIFICATION_SEEK_AUDIO"
#define NOTIFICATION_CHANGE_PLAY_MODE @"NOTIFICATION_CHANGE_PLAY_MODE"
#define NOTIFICATION_CHANGE_SHUFFLE_MODE @"NOTIFICATION_CHANGE_SHUFFLE_MODE"

#define NOTIFICATION_BECOME_ACTIVATE @"NOTIFICATION_BECOME_ACTIVATE"
#define NOTIFICATION_NO_NETWORK @"NOTIFICATION_NO_NETWORK"

#define NOTIFICATION_DOWNLOAD_ALBUM_START @"NOTIFICATION_DOWNLOAD_ALBUM_START"
#define NOTIFICATION_DOWNLOAD_ALBUM_STATE @"NOTIFICATION_DOWNLOAD_ALBUM_STATE"
#define NOTIFICATION_DOWNLOAD_ALBUM_COMPLETE @"NOTIFICATION_DOWNLOAD_ALBUM_COMPLETE"

#endif /* PConstants_h */
